# This file was generated by GoReleaser. DO NOT EDIT.
cask "angry-bear" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "9522ac2bdf62fa23fe9de7b4301e7b038637651023fd0c93cd33c29610e26f35"
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v#{version}/angry-bear_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "65773c6461d18ede3ae0cb9975dd0e801ea4ea64cca55c5a8c13151ca1a4d7ed"
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v#{version}/angry-bear_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2224c2c0d7e81c86a7ff899671926191986cc0c80ffd41e866f64a2d41a43706"
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v#{version}/angry-bear_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "90f9e2e39cb15ab42c948df2f26525503cd0eefe13fd8ada685497d669b9e6cc"
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v#{version}/angry-bear_#{version}_linux_arm64.tar.gz"
    end
  end

  name "angry-bear"
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/bluebear-io/angry-bear"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "angry-bear"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/angry-bear"]
    end
  end

  # No zap stanza required

end
