# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AngryBear < Formula
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/bluebear-io/angry-bear"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v0.12.0/angry-bear_0.12.0_darwin_amd64.tar.gz"
      sha256 "0dfd97e2f32b133f8aadb8a92034571c3d32eb2cb14a6a2e6be7fc1755a04314"

      define_method(:install) do
        bin.install "angry-bear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v0.12.0/angry-bear_0.12.0_darwin_arm64.tar.gz"
      sha256 "aa7403d6ed781905828a52c2223c4b7a24888f06d1d74ebee1f77dc76fcc4055"

      define_method(:install) do
        bin.install "angry-bear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v0.12.0/angry-bear_0.12.0_linux_amd64.tar.gz"
      sha256 "09d1341e1b44567765d2f6030ed585b71e64e896c887f1ac41ca5302d7ba1318"
      define_method(:install) do
        bin.install "angry-bear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v0.12.0/angry-bear_0.12.0_linux_arm64.tar.gz"
      sha256 "6e0e6d724459231d171a3e0bcb93e833adc54efc7bb184874441c63042303426"
      define_method(:install) do
        bin.install "angry-bear"
      end
    end
  end

  test do
    system "#{bin}/angry-bear", "version"
  end
end
